Anforderungen = [{
deutsch: 'Sitka-Fichte',
latein: 'Picea sitchensis',
frost: '-26',
gartenGross: 'x',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: '',
hinweis: 'weder aktuell noch in Zukunft regionaltypisch - Lebensraum nur für wenige Tierarten; nicht resistente Sorten sind anfällig für Schädlinge und/oder Krankheiten; Flachwurzler, d.h. windwurfgefährdet, hoher Bewässerungsbedarf, Begrünung im Wurzelbereich kaum möglich  '
},{
deutsch: 'Nordmann-Tanne',
latein: 'Abies nordmanniana',
frost: '-26',
gartenGross: 'x',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: '',
hinweis: 'weder aktuell noch in Zukunft regionaltypisch - Lebensraum nur für wenige Tierarten; einige Sorten sind spätfrostgefährdet; nicht resistente Sorten sind anfällig für Schädlinge und/oder Krankheiten '
},{
deutsch: 'Feuer-Ahorn',
latein: 'Acer tataricum',
frost: '-20',
gartenGross: 'x',
gartenKlein: 'x',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: '',
parks: '',
landschaft: '',
hinweis: 'weder aktuell noch in Zukunft regionaltypisch - Lebensraum nur für wenige Tierarten; einige Sorten sind spätfrostgefährdet; nicht resistente Sorten sind anfällig für Schädlinge und/oder Krankheiten '
},{
deutsch: 'Silber-Linde',
latein: 'Tilia argentea',
frost: '-20',
gartenGross: '',
gartenKlein: '',
strassenBreit: 'x',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: '',
hinweis: 'weder aktuell noch in Zukunft regionaltypisch - Lebensraum nur für wenige Tierarten; einige Sorten sind spätfrostgefährdet; Honigtau verdreckt parkende Fahrzeuge'
},{
deutsch: 'Dalechamp-Eiche',
latein: 'Quercus dalechampii',
frost: '-20',
gartenGross: '',
gartenKlein: '',
strassenBreit: 'x',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: 'x',
hinweis: 'einige Sorten sind frostgefährdet; harte Früchte können Fahrzeugkarossen verbeulen; Pollen können Allergie auslösen'
},{
deutsch: 'Ungarische Eiche',
latein: 'Quercus frainetto',
frost: '-15',
gartenGross: '',
gartenKlein: '',
strassenBreit: 'x',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: 'x',
hinweis: 'einige Sorten sind frostgefährdet; harte Früchte können Fahrzeugkarossen verbeulen; Pollen können Allergie auslösen '
},{
deutsch: 'Trauben-Eiche',
latein: 'Quercus petraea',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: 'x',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: 'x',
hinweis: 'nicht resistente Sorten sind anfällig für Schädlinge und/oder Krankheiten; harte Früchte können Fahrzeugkarossen verbeulen; Pollen können Allergie auslösen  '
},{
deutsch: 'Sommer-Linde',
latein: 'Tilia platyphyllos',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: 'x',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: 'x',
hinweis: 'Honigtau verdreckt parkende Fahrzeuge'
},{
deutsch: 'Hybrid-Pappel',
latein: 'Populus euramericana',
frost: '-21',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: '',
hecken: 'x',
parks: '',
landschaft: '',
hinweis: 'weder aktuell noch in Zukunft regionaltypisch - Lebensraum nur für wenige Tierarten; Ausbreitungsdrang über Wurzelschösslinge; Pollen können Allergie auslösen; Flachwurzler, d.h. windwurfgefährdet, hoher Bewässerungsbedarf, Begrünung im Wurzelbereich kaum möglich; Wurzeln können in Rohre eindringen und/oder sie zerstören'
},{
deutsch: 'Blumen-Esche',
latein: 'Fraxinus ornus',
frost: '-26',
gartenGross: 'x',
gartenKlein: 'x',
strassenBreit: 'x',
strassenSchmal: 'x',
gartenEinzel: 'x',
hecken: '',
parks: '',
landschaft: '',
hinweis: 'Pollen können Allergie auslösen'
},{
deutsch: 'Feld-Ulme',
latein: 'Ulmus minor',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: 'x',
hinweis: 'nicht resistente Sorten sind anfällig für Schädlinge und/oder Krankheiten '
},{
deutsch: 'Hainbuche',
latein: 'Carpinus betulus',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: 'x',
strassenSchmal: '',
gartenEinzel: '',
hecken: 'x',
parks: 'x',
landschaft: 'x',
hinweis: 'Pollen können Allergie auslösen; Flachwurzler, d.h. windwurfgefährdet, hoher Bewässerungsbedarf, Begrünung im Wurzelbereich kaum möglich '
},{
deutsch: 'Gemeine Esche',
latein: 'Fraxinus excelsior',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: 'x',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: 'x',
hinweis: 'nicht resistente Sorten sind anfällig für Schädlinge und/oder Krankheiten; Pollen können Allergie auslösen '
},{
deutsch: 'Berg-Ulme',
latein: 'Ulmus glabra',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: 'x',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: 'x',
hinweis: 'nicht resistente Sorten sind anfällig für Schädlinge und/oder Krankheiten '
},{
deutsch: 'Flatter-Ulme',
latein: 'Ulmus laevis',
frost: '-20',
gartenGross: '',
gartenKlein: '',
strassenBreit: 'x',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: 'x',
hinweis: ''
},{
deutsch: 'Ahornblättrige Platane',
latein: 'Platanus acerifolia',
frost: '-20',
gartenGross: '',
gartenKlein: '',
strassenBreit: 'x',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: '',
landschaft: '',
hinweis: 'weder aktuell noch in Zukunft regionaltypisch - Lebensraum nur für wenige Tierarten; einige Sorten sind frostgefährdet; harte Früchte können Fahrzeugkarossen verbeulen; Pollen können Allergie auslösen '
},{
deutsch: 'Gemeine Kiefer',
latein: 'Pinus sylvestris sylvestris',
frost: '-41',
gartenGross: 'x',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: 'x',
hinweis: ''
},{
deutsch: 'Sand-Birke',
latein: 'Betula pendula',
frost: '-26',
gartenGross: 'x',
gartenKlein: '',
strassenBreit: 'x',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: 'x',
hinweis: 'Pollen können Allergie auslösen; Flachwurzler, d.h. windwurfgefährdet, hoher Bewässerungsbedarf, Begrünung im Wurzelbereich kaum möglich '
},{
deutsch: 'Gemeine Fichte',
latein: 'Picea abies',
frost: '-41',
gartenGross: 'x',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: '',
landschaft: '',
hinweis: 'weder aktuell noch in Zukunft regionaltypisch - Lebensraum nur für wenige Tierarten; nicht resistente Sorten sind anfällig für Schädlinge und/oder Krankheiten; Flachwurzler, d.h. windwurfgefährdet, hoher Bewässerungsbedarf, Begrünung im Wurzelbereich kaum möglich '
},{
deutsch: 'Weiß-Tanne',
latein: 'Abies alba',
frost: '-26',
gartenGross: 'x',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: '',
hinweis: 'nicht resistente Sorten sind anfällig für Schädlinge und/oder Krankheiten; empfindlich gegenüber Luftschadstoffen;'
},{
deutsch: 'Stiel-Eiche',
latein: 'Quercus robur',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: 'x',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: 'x',
hinweis: 'nicht resistente Sorten sind anfällig für Schädlinge und/oder Krankheiten; harte Früchte können Fahrzeugkarossen verbeulen; Pollen können Allergie auslösen '
},{
deutsch: 'Bruch-Weide',
latein: 'Salix fragilis',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: '',
landschaft: 'x',
hinweis: 'Pollen können Allergie auslösen'
},{
deutsch: 'Roterle',
latein: 'Alnus glutinosa',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: '',
landschaft: 'x',
hinweis: 'Pollen können Allergie auslösen'
},{
deutsch: 'Flaum-Eiche',
latein: 'Quercus pubescens',
frost: '-20',
gartenGross: 'x',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: 'x',
hinweis: 'einige Sorten sind spätfrostgefährdet; harte Früchte können Fahrzeugkarossen verbeulen; Pollen können Allergie auslösen'
},{
deutsch: 'Silber-Weide',
latein: 'Salix alba',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: 'x',
hinweis: 'Pollen können Allergie auslösen'
},{
deutsch: 'Lorbeer-Weide',
latein: 'Salix pentandra',
frost: '-26',
gartenGross: 'x',
gartenKlein: 'x',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: '',
landschaft: 'x',
hinweis: 'Pollen können Allergie auslösen'
},{
deutsch: 'Schwarz-Pappel',
latein: 'Populus nigra',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: '',
landschaft: 'x',
hinweis: 'Ausbreitungsdrang über Wurzelschösslinge; Pollen können Allergie auslösen; Flachwurzler, d.h. windwurfgefährdet, hoher Bewässerungsbedarf, Begrünung im Wurzelbereich kaum möglich '
},{
deutsch: 'Speierling',
latein: 'Sorbus domestica',
frost: '-20',
gartenGross: 'x',
gartenKlein: 'x',
strassenBreit: '',
strassenSchmal: 'x',
gartenEinzel: 'x',
hecken: '',
parks: 'x',
landschaft: '',
hinweis: 'einige Sorten sind frostgefährdet; '
},{
deutsch: 'Kornelkirsche',
latein: 'Cornus mas',
frost: '-26',
gartenGross: 'x',
gartenKlein: 'x',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: 'x',
parks: 'x',
landschaft: '',
hinweis: ''
},{
deutsch: 'Espe',
latein: 'Populus tremula',
frost: '-21',
gartenGross: 'x',
gartenKlein: 'x',
strassenBreit: '',
strassenSchmal: 'x',
gartenEinzel: '',
hecken: '',
parks: '',
landschaft: 'x',
hinweis: 'Ausbreitungsdrang über Wurzelschösslinge; Pollen können Allergie auslösen'
},{
deutsch: 'Echte Mehlbeere',
latein: 'Sorbus aria',
frost: '-40',
gartenGross: 'x',
gartenKlein: 'x',
strassenBreit: '',
strassenSchmal: 'x',
gartenEinzel: 'x',
hecken: '',
parks: 'x',
landschaft: '',
hinweis: ''
},{
deutsch: 'Wildapfel',
latein: 'Malus sylvestris',
frost: '-19',
gartenGross: 'x',
gartenKlein: 'x',
strassenBreit: '',
strassenSchmal: 'x',
gartenEinzel: 'x',
hecken: 'x',
parks: 'x',
landschaft: '',
hinweis: 'einige Sorten sind spätfrostgefährdet; '
},{
deutsch: 'Berg-Kiefer',
latein: 'Pinus mugo',
frost: '-26',
gartenGross: 'x',
gartenKlein: 'x',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: '',
hinweis: 'weder aktuell noch in Zukunft regionaltypisch - Lebensraum nur für wenige Tierarten; '
},{
deutsch: 'Rotbuche',
latein: 'Fagus sylvatica',
frost: '-26',
gartenGross: 'x',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: '',
hecken: 'x',
parks: 'x',
landschaft: 'x',
hinweis: 'Pollen können Allergie auslösen'
},{
deutsch: 'Schwarz-Kiefer',
latein: 'Pinus nigra',
frost: '-26',
gartenGross: 'x',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: '',
landschaft: '',
hinweis: 'weder aktuell noch in Zukunft regionaltypisch - Lebensraum nur für wenige Tierarten; '
},{
deutsch: 'Eberesche',
latein: 'Sorbus aucuparia',
frost: '-26',
gartenGross: 'x',
gartenKlein: 'x',
strassenBreit: '',
strassenSchmal: 'x',
gartenEinzel: 'x',
hecken: '',
parks: 'x',
landschaft: 'x',
hinweis: ''
},{
deutsch: 'Baum-Hasel',
latein: 'Corylus colurna',
frost: '-26',
gartenGross: 'x',
gartenKlein: 'x',
strassenBreit: '',
strassenSchmal: 'x',
gartenEinzel: 'x',
hecken: '',
parks: 'x',
landschaft: '',
hinweis: 'Pollen können Allergie auslösen'
},{
deutsch: 'Zwerg-Mandel',
latein: 'Prunus tenella',
frost: '-20',
gartenGross: '',
gartenKlein: 'x',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: '',
parks: '',
landschaft: '',
hinweis: 'nicht resistente Sorten sind anfällig für Schädlinge und/oder Krankheiten '
},{
deutsch: 'Ölweiden-Birne',
latein: 'Pyrus eleagnifolia',
frost: '-17',
gartenGross: '',
gartenKlein: 'x',
strassenBreit: '',
strassenSchmal: 'x',
gartenEinzel: 'x',
hecken: 'x',
parks: 'x',
landschaft: '',
hinweis: 'einige Sorten sind frostgefährdet; '
},{
deutsch: 'Elsbeere',
latein: 'Sorbus torminalis',
frost: '-26',
gartenGross: 'x',
gartenKlein: 'x',
strassenBreit: '',
strassenSchmal: 'x',
gartenEinzel: 'x',
hecken: '',
parks: 'x',
landschaft: 'x',
hinweis: ''
},{
deutsch: 'Feld-Ahorn',
latein: 'Acer campestre',
frost: '-26',
gartenGross: 'x',
gartenKlein: '',
strassenBreit: 'x',
strassenSchmal: '',
gartenEinzel: '',
hecken: 'x',
parks: 'x',
landschaft: 'x',
hinweis: ''
},{
deutsch: 'Ess-Kastanie',
latein: 'Castanea sativa',
frost: '-15',
gartenGross: 'x',
gartenKlein: 'x',
strassenBreit: '',
strassenSchmal: 'x',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: '',
hinweis: 'einige Sorten sind frostgefährdet; harte Früchte können Fahrzeugkarossen verbeulen; Pollen können Allergie auslösen '
},{
deutsch: 'Zerr-Eiche',
latein: 'Quercus cerris',
frost: '-20',
gartenGross: 'x',
gartenKlein: '',
strassenBreit: 'x',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: '',
hinweis: 'Pollen können Allergie auslösen'
},{
deutsch: 'Winter-Linde',
latein: 'Tilia cordata',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: 'x',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: 'x',
hinweis: 'Honigtau verdreckt parkende Fahrzeuge'
},{
deutsch: 'Berg-Ahorn',
latein: 'Acer pseudoplatanus',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: 'x',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: 'x',
hinweis: ''
},{
deutsch: 'Spitz-Ahorn',
latein: 'Acer platanoides',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: 'x',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: 'x',
hinweis: ''
},{
deutsch: 'Weichselkirsche',
latein: 'Prunus mahaleb',
frost: '-20',
gartenGross: 'x',
gartenKlein: 'x',
strassenBreit: '',
strassenSchmal: 'x',
gartenEinzel: 'x',
hecken: '',
parks: 'x',
landschaft: 'x',
hinweis: ''
},{
deutsch: 'Walnuss',
latein: 'Juglans regia',
frost: '-20',
gartenGross: 'x',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: '',
hinweis: 'harte Früchte können Fahrzeugkarossen verbeulen; '
},{
deutsch: 'Wild-Birne',
latein: 'Pyrus pyraster',
frost: '-26',
gartenGross: 'x',
gartenKlein: 'x',
strassenBreit: '',
strassenSchmal: 'x',
gartenEinzel: 'x',
hecken: 'x',
parks: 'x',
landschaft: 'x',
hinweis: 'nicht resistente Sorten sind anfällig für Schädlinge und/oder Krankheiten '
},{
deutsch: 'Steppen-Kirsche',
latein: 'Prunus fruticosa',
frost: '-20',
gartenGross: 'x',
gartenKlein: 'x',
strassenBreit: '',
strassenSchmal: 'x',
gartenEinzel: 'x',
hecken: '',
parks: 'x',
landschaft: '',
hinweis: ''
},{
deutsch: 'Öhrchen-Weide',
latein: 'Salix aurita',
frost: '-26',
gartenGross: 'x',
gartenKlein: 'x',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: 'x',
parks: 'x',
landschaft: 'x',
hinweis: 'Pollen können Allergie auslösen'
},{
deutsch: 'Rot-Eiche',
latein: 'Quercus rubra',
frost: '-20',
gartenGross: '',
gartenKlein: '',
strassenBreit: 'x',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: '',
hinweis: 'weder aktuell noch in Zukunft regionaltypisch - Lebensraum nur für wenige Tierarten; Pollen können Allergie auslösen'
},{
deutsch: 'Douglasie',
latein: 'Pseudotsuga menziesii',
frost: '-26',
gartenGross: 'x',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: '',
hinweis: 'weder aktuell noch in Zukunft regionaltypisch - Lebensraum nur für wenige Tierarten; Flachwurzler, d.h. windwurfgefährdet, hoher Bewässerungsbedarf, Begrünung im Wurzelbereich kaum möglich '
},{
deutsch: 'Europäische Lärche',
latein: 'Larix decidua',
frost: '-26',
gartenGross: 'x',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: '',
hinweis: 'weder aktuell noch in Zukunft regionaltypisch - Lebensraum nur für wenige Tierarten; '
},{
deutsch: 'Robinie',
latein: 'Robinia pseudoacacia',
frost: '-20',
gartenGross: '',
gartenKlein: '',
strassenBreit: 'x',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: '',
hinweis: 'weder aktuell noch in Zukunft regionaltypisch - Lebensraum nur für wenige Tierarten; Ausbreitungsdrang über Wurzelschösslinge; alle Teile giftig'
},{
deutsch: 'Wacholder',
latein: 'Juniperus spec. (alle Arten)',
frost: '-26',
gartenGross: 'x',
gartenKlein: 'x',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: '',
parks: 'x',
landschaft: '',
hinweis: ''
},{
deutsch: 'Zwergmispeln',
latein: 'Cotoneaster spec. (alle Arten)',
frost: '-20',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: '',
parks: 'x',
landschaft: '',
hinweis: 'weder aktuell noch in Zukunft regionaltypisch - Lebensraum nur für wenige Tierarten; '
},{
deutsch: 'Kirschlorbeer',
latein: 'Laurocerasus spec. (alle Arten)',
frost: '-20',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: 'x',
parks: 'x',
landschaft: '',
hinweis: 'weder aktuell noch in Zukunft regionaltypisch - Lebensraum nur für wenige Tierarten; einige Sorten sind frostgefährdet; Blätter und Samenkern giftig'
},{
deutsch: 'Weißdorn',
latein: 'Crataegus spec. (alle Arten)',
frost: '-26',
gartenGross: 'x',
gartenKlein: 'x',
strassenBreit: '',
strassenSchmal: 'x',
gartenEinzel: 'x',
hecken: 'x',
parks: 'x',
landschaft: 'x',
hinweis: ''
},{
deutsch: 'Liguster',
latein: 'Ligustrum spec. (alle Arten)',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: 'x',
parks: 'x',
landschaft: '',
hinweis: ''
},{
deutsch: 'Rhododendron',
latein: 'Rhododendron spec. (alle Arten)',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: 'x',
parks: 'x',
landschaft: '',
hinweis: 'weder aktuell noch in Zukunft regionaltypisch - Lebensraum nur für wenige Tierarten; alle Teile giftig'
},{
deutsch: 'Hundsrose',
latein: 'Rosa canina',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: 'x',
parks: 'x',
landschaft: 'x',
hinweis: ''
},{
deutsch: 'Wilde Süß-Kirsche',
latein: 'Prunus avium',
frost: '-26',
gartenGross: 'x',
gartenKlein: 'x',
strassenBreit: '',
strassenSchmal: 'x',
gartenEinzel: 'x',
hecken: '',
parks: 'x',
landschaft: 'x',
hinweis: ''
},{
deutsch: 'Roter Hartriegel',
latein: 'Cornus sanguinea',
frost: '-41',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: 'x',
parks: 'x',
landschaft: 'x',
hinweis: ''
},{
deutsch: 'Gemeiner Schneeball',
latein: 'Viburnum opulus',
frost: '-41',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: 'x',
parks: 'x',
landschaft: 'x',
hinweis: 'nicht resistente Sorten sind anfällig für Schädlinge und/oder Krankheiten '
},{
deutsch: 'Stechpalme',
latein: 'Ilex aquifolium',
frost: '-15',
gartenGross: 'x',
gartenKlein: 'x',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: '',
parks: 'x',
landschaft: '',
hinweis: 'weder aktuell noch in Zukunft regionaltypisch - Lebensraum nur für wenige Tierarten; einige Sorten sind spätfrostgefährdet; nicht resistente Sorten sind anfällig für Schädlinge und/oder Krankheiten; alle Teile giftig '
},{
deutsch: 'Schwarzer Holunder',
latein: 'Sambucus nigra',
frost: '-41',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: 'x',
parks: 'x',
landschaft: 'x',
hinweis: 'Beeren (roh), Blätter, Triebe, Rinde giftig'
},{
deutsch: 'Himbeere',
latein: 'Rubus idaeus',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: 'x',
parks: '',
landschaft: 'x',
hinweis: 'Ausbreitungsdrang über Wurzelschösslinge'
},{
deutsch: 'Schwarze Johannisbeere',
latein: 'Ribes nigrum',
frost: '-20',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: 'x',
parks: '',
landschaft: 'x',
hinweis: ''
},{
deutsch: 'Rote Johannisbeere',
latein: 'Ribes vulgare',
frost: '-20',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: 'x',
parks: '',
landschaft: 'x',
hinweis: 'einige Sorten sind spätfrostgefährdet; '
},{
deutsch: 'Brombeere',
latein: 'Rubus fruticosus',
frost: '-21',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: 'x',
parks: '',
landschaft: 'x',
hinweis: 'Ausbreitungsdrang über Wurzelschösslinge'
},{
deutsch: 'Flieder',
latein: 'Syringa vulgaris',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: 'x',
parks: 'x',
landschaft: '',
hinweis: ''
},{
deutsch: 'Schlehe',
latein: 'Prunus spinosa',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: 'x',
parks: 'x',
landschaft: 'x',
hinweis: 'Ausbreitungsdrang über Wurzelschösslinge'
},{
deutsch: 'Haselnuss',
latein: 'Corylus avellana',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: 'x',
parks: 'x',
landschaft: 'x',
hinweis: ''
},{
deutsch: 'Sal-Weide',
latein: 'Salix caprea',
frost: '-41',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: '',
parks: '',
landschaft: 'x',
hinweis: 'Pollen können Allergie auslösen'
},{
deutsch: 'Korb-Weide',
latein: 'Salix viminalis',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: '',
parks: '',
landschaft: 'x',
hinweis: 'Ausbreitungsdrang über Wurzelschösslinge; Pollen können Allergie auslösen'
},{
deutsch: 'Purpur-Weide',
latein: 'Salix purpurea',
frost: '-41',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: 'x',
parks: 'x',
landschaft: 'x',
hinweis: 'Ausbreitungsdrang über Wurzelschösslinge; Pollen können Allergie auslösen'
},{
deutsch: 'Berberitze',
latein: 'Berberis vulgaris',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: 'x',
parks: 'x',
landschaft: 'x',
hinweis: 'nicht resistente Sorten sind anfällig für Schädlinge und/oder Krankheiten '
},{
deutsch: 'Buchsbaum',
latein: 'Buxus sempervirens',
frost: '-20',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: 'x',
parks: 'x',
landschaft: '',
hinweis: 'nicht resistente Sorten sind anfällig für Schädlinge und/oder Krankheiten; alle Teile giftig '
},{
deutsch: 'Eibe',
latein: 'Taxus baccata',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: 'x',
hecken: 'x',
parks: 'x',
landschaft: 'x',
hinweis: 'Kern der Beere, Blattwerk, Rinde, Holz, Wurzel giftig'
},{
deutsch: 'Weiße Rosskastanie',
latein: 'Aesculus hippocastanum',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: 'x',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: '',
hinweis: 'weder aktuell noch in Zukunft regionaltypisch - Lebensraum nur für wenige Tierarten; anfällig für Schädlinge und/oder Krankheiten; harte Früchte können Fahrzeugkarossen verbeulen '
},{
deutsch: 'Fleischrote Rosskastanie',
latein: 'Aesculus × carnea',
frost: '-26',
gartenGross: '',
gartenKlein: '',
strassenBreit: 'x',
strassenSchmal: '',
gartenEinzel: '',
hecken: '',
parks: 'x',
landschaft: '',
hinweis: 'weder aktuell noch in Zukunft regionaltypisch - Lebensraum nur für wenige Tierarten; harte Früchte können Fahrzeugkarossen verbeulen '
},{
deutsch: 'Lebensbaum',
latein: 'Thuja spec. (alle Arten)',
frost: '-26',
gartenGross: 'x',
gartenKlein: '',
strassenBreit: '',
strassenSchmal: '',
gartenEinzel: '',
hecken: 'x',
parks: 'x',
landschaft: '',
hinweis: 'weder aktuell noch in Zukunft regionaltypisch - Lebensraum nur für wenige Tierarten; Flachwurzler, d.h. windwurfgefährdet, hoher Bewässerungsbedarf, Begrünung im Wurzelbereich kaum möglich; Zweige und Zapfen giftig'
}]